////////////////////////////////////////
// Roenall Army
////////////////////////////////////////

IF
  Die()
THEN
  RESPONSE #100
    IncrementGlobal("b#roen","GLOBAL",1)
END

////////////////////////////////////////
// Detect Enemy
////////////////////////////////////////

IF
  Heard([ANYONE],111)
THEN
  RESPONSE #100
    MoveToObject(NearestEnemyOf(Myself))
END

IF
  Detect([PC])
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  OR(6)
    !See(LastSeenBy(Myself))
    StateCheck([PC],STATE_INVISIBLE)
    StateCheck([PC],STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,26703)
    MoveToObject(LastSeenBy(Myself))
END

////////////////////////////////////////
// Hide/Invisible
////////////////////////////////////////

IF
  See(NearestEnemyOf(Myself))
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  HasItem("potn10",Myself)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,46150)
    UseItem("potn10",Myself)
    Continue()
END

IF
  See([PC])
  Allegiance(Myself,ENEMY)
  !Range(LastSeenBy(Myself),1)
  OR(2)
    StateCheck(Myself,STATE_INVISIBLE)
    StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    MoveToObject(LastSeenBy(Myself))
    Continue()
END

////////////////////////////////////////
// Use Specials
////////////////////////////////////////

IF
  Range(NearestEnemyOf(Myself),1)
  Allegiance(Myself,ENEMY)
  HaveSpell(ASSASSIN_POISON)
  !GlobalTimerNotExpired("UseSpecial","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("UseSpecial","LOCALS",12)
    Spell(Myself,ASSASSIN_POISON)
    Continue()
END

////////////////////////////////////////
// Attack Enemy/Backstab
////////////////////////////////////////

IF
  Range(NearestEnemyOf(Myself),1)
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    Attack(LastSeenBy(Myself))
END

////////////////////////////////////////
// Create & Use POTN52
////////////////////////////////////////

IF
  HPPercentLT(Myself,76)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    GiveItemCreate("potn52",Myself,1,0,0)
    DisplayStringHead(Myself,46150)
    UseItem("potn52",Myself)
END