////////////////////////////////////////
// Roenall Army
////////////////////////////////////////

IF
  Die()
THEN
  RESPONSE #100
    IncrementGlobal("b#roen","GLOBAL",1)
END

////////////////////////////////////////
// Attack
////////////////////////////////////////

IF
  OR(9)
    See(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(ThirdNearestEnemyOfType([0.0.0.SORCERER]))
    See(SecondNearestEnemyOfType([0.0.0.SORCERER]))
    See(NearestEnemyOfType([0.0.0.SORCERER]))
    See(ThirdNearestEnemyOfType([0.0.0.BARD_ALL]))
    See(SecondNearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
  !Range(LastSeenBy(Myself),7)
THEN
  RESPONSE #100
    EquipRanged()
    AttackReevaluate(LastSeenBy(Myself),15)
END

IF
  OR(9)
    See(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(ThirdNearestEnemyOfType([0.0.0.SORCERER]))
    See(SecondNearestEnemyOfType([0.0.0.SORCERER]))
    See(NearestEnemyOfType([0.0.0.SORCERER]))
    See(ThirdNearestEnemyOfType([0.0.0.BARD_ALL]))
    See(SecondNearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
  Range(LastSeenBy(Myself),7)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(LastSeenBy(Myself),30)
END

IF
  See(NearestEnemyOfType([PC]))
  Allegiance(LastSeenBy(Myself),GOODCUTOFF)
  !Range(LastSeenBy(Myself),7)
  ActionListEmpty()
THEN
  RESPONSE #100
    EquipRanged()
    Attack(LastSeenBy(Myself))
END

IF
  See(NearestEnemyOfType([PC]))
  Allegiance(LastSeenBy(Myself),GOODCUTOFF)
  Range(LastSeenBy(Myself),7)
  ActionListEmpty()
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    Attack(LastSeenBy(Myself))
END

////////////////////////////////////////
// Use Potions
////////////////////////////////////////

IF
  HPPercentLT(Myself,76)
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    GiveItemCreate("potn52",Myself,1,0,0)
    DisplayStringHead(Myself,46150)
    UseItem("potn52",Myself)
END