IF
    See(NearestEnemyOf(Myself))
    Global("prep","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("prep","LOCALS",1)
        ApplySpell(Myself,CLERIC_DEFENSIVE_HARMONY)
        ForceSpell(Myself,NPC_BLADE_BARRIER)
        ForceSpell(Myself,CLERIC_SILENCE_15_FOOT)
        ForceSpell(Myself,CLERIC_INVISIBILITY_PURGE)
        Continue()
END

IF
    HPLT(Myself,20)
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_EARTHQUAKE)
        Continue()
END

IF
    HPPercentLT(Myself,50)
THEN
    RESPONSE #100
        ForceSpell(Myself,CLERIC_SANCTUARY)
        ForceSpell(Myself,CLERIC_HEAL)
        Spell(Myself,CLERIC_PROTECTION_FROM_FIRE)
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_NPC_SYMBOL_STUN)
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_HARM)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_HARM)
        AttackOneRound(NearestEnemyOf(Myself))
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_FLAME_STRIKE)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_FLAME_STRIKE)
        Continue()
END

IF
    Detect(NearestEnemyOf(Myself))
    !See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_TRUE_SIGHT)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_TRUE_SIGHT)
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_SLAY_LIVING)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_SLAY_LIVING)
        AttackOneRound(NearestEnemyOf(Myself))
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_FLAME_STRIKE)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_FLAME_STRIKE)
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_ANIMATE_DEAD)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_ANIMATE_DEAD)
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_BLADE_BARRIER)
    Global("blade","LOCALS",0)
THEN
    RESPONSE #100
        Spell(Myself,NPC_BLADE_BARRIER)
        SetGlobal("blade","LOCALS",1)
END

IF
    HaveSpell(CLERIC_SILENCE_15_FOOT)
    OR(2)
        See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
        See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    !Range(LastSeenBy(Myself),20)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_CHARM_PERSON)
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_CHARM_PERSON)
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_HOLD_PERSON)
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_HOLD_PERSON)
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    !Range(LastSeenBy(Myself),4)
    HPPercentLT(Myself,20)
    HaveSpell(CLERIC_HEAL)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_HEAL)
END

IF
    See(NearestEnemyOf(Myself))
    !Range(LastSeenBy(Myself),10)
THEN
    RESPONSE #100
        EquipRanged()
        AttackReevaluate(NearestEnemyOf(Myself),30)
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    Range(LastSeenBy(Myself),10)
THEN
    RESPONSE #100
        EquipMostDamagingMelee()
        AttackReevaluate(NearestEnemyOf(Myself),30)
        Continue()
END

