////////////////////////////////////////
// Pateus Cairbre (Inquisitor)
////////////////////////////////////////

////////////////////////////////////////
// Go Hostile
////////////////////////////////////////

IF
  Allegiance("b#knit01",ENEMY)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Enemy()
END

////////////////////////////////////////
// Detect Enemy
////////////////////////////////////////

// Hear

IF
  Heard([ANYONE],111)
THEN
  RESPONSE #100
    MoveToObject(NearestEnemyOf(Myself))
END

// Sense (Can Cast)

IF
  Detect([PC])
  !See(LastSeenBy(Myself))
  Allegiance(Myself,ENEMY)
  Allegiance(LastSeenBy(Myself),PC)
  OR(3)
    !See(LastSeenBy(Myself))
    StateCheck([PC],STATE_INVISIBLE)
    StateCheck([PC],STATE_IMPROVEDINVISIBILITY)
  HaveSpell(INQUIS_TRUE_SIGHT)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    DisplayStringHead(Myself,26703)
    ForceSpell(Myself,INQUIS_TRUE_SIGHT)
END

// Sense (Cannot Cast)

IF
  Detect([PC])
  !See(LastSeenBy(Myself))
  Allegiance(Myself,ENEMY)
  Allegiance(LastSeenBy(Myself),PC)
  OR(3)
    !See(LastSeenBy(Myself))
    StateCheck([PC],STATE_INVISIBLE)
    StateCheck([PC],STATE_IMPROVEDINVISIBILITY)
  !HaveSpell(INQUIS_TRUE_SIGHT)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,26703)
    MoveToObject(LastSeenBy(Myself))
END

////////////////////////////////////////
// Use Potions
////////////////////////////////////////

// Extra Healing

IF
  HPPercentLT(Myself,76)
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    GiveItemCreate("potn52",Myself,1,0,0)
    DisplayStringHead(Myself,46150)
    UseItem("potn52",Myself)
END

// Frost Giant Strength

IF
  CheckStatLT(Myself,24,STR)
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    GiveItemCreate("potn07",Myself,1,0,0)
    DisplayStringHead(Myself,46150)
    UseItem("potn07",Myself)
END

////////////////////////////////////////
// Attack Enemy
////////////////////////////////////////

IF
  See([PC])
  Allegiance(Myself,ENEMY)
  Allegiance(LastSeenBy(Myself),PC)
THEN
  RESPONSE #100
    Attack(LastSeenBy(Myself))
END
