////////////////////////////////////////
// Edrin (Monk)
////////////////////////////////////////

////////////////////////////////////////
// Go Hostile
////////////////////////////////////////

IF
  Allegiance("b#knit01",ENEMY)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Enemy()
END

////////////////////////////////////////
// Detect Enemy
////////////////////////////////////////

// Hear

IF
  Heard([ANYONE],111)
THEN
  RESPONSE #100
    MoveToObject(NearestEnemyOf(Myself))
END

// Sense

IF
  Detect([PC])
  !See(LastSeenBy(Myself))
  Allegiance(Myself,ENEMY)
  Allegiance(LastSeenBy(Myself),PC)
  OR(6)
    !See(LastSeenBy(Myself))
    StateCheck([PC],STATE_INVISIBLE)
    StateCheck([PC],STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,26703)
    MoveToObject(LastSeenBy(Myself))
END

////////////////////////////////////////
// Use Potions
////////////////////////////////////////

// Lay On Hands

IF
  HPPercentLT(Myself,26)
  Allegiance(Myself,ENEMY)
  HaveSpell(MONK_LAY_ON_HANDS)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    ForceSpell(Myself,MONK_LAY_ON_HANDS)
END

// Extra Healing

IF
  HPPercentLT(Myself,76)
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    GiveItemCreate("potn52",Myself,1,0,0)
    DisplayStringHead(Myself,46150)
    UseItem("potn52",Myself)
END

// Frost Giant Strength

IF
  CheckStatLT(Myself,24,STR)
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    GiveItemCreate("potn07",Myself,1,0,0)
    DisplayStringHead(Myself,46150)
    UseItem("potn07",Myself)
END

////////////////////////////////////////
// Monk Stunning Blow/QP &/or Attack
////////////////////////////////////////

// Quivering Palm

IF
  See([PC])
  Allegiance(Myself,ENEMY)
  Allegiance(LastSeenBy(Myself),PC)
  CheckStatGT(LastSeenBy(Myself),9,SAVEVSDEATH)
  Range(LastSeenBy(Myself),6)
  HaveSpell(MONK_QUIVERING_PALM)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    ForceSpell(Myself,MONK_QUIVERING_PALM)
END

// Stunning Blow

IF
  See([PC])
  Allegiance(Myself,ENEMY)
  Allegiance(LastSeenBy(Myself),PC)
  Range(LastSeenBy(Myself),6)
  HaveSpell(MONK_STUNNING_BLOW)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    ForceSpell(Myself,MONK_STUNNING_BLOW)
END

// Attack

IF
  See([PC])
  Allegiance(Myself,ENEMY)
  Allegiance(LastSeenBy(Myself),PC)
THEN
  RESPONSE #100
    Attack(LastSeenBy(Myself))
END
