IF
    !InMyArea(Player1)
    CombatCounter(0)
THEN
    RESPONSE #100
END

IF
  Allegiance(Myself,ENEMY)
  !Dead("draug")
  !See("draug")
THEN
  RESPONSE #100
    ReallyForceSpell("draug",WIZARD_DIMENSION_DOOR)
END

IF
  Allegiance(Myself,ENEMY)
  Dead("draug")
  !Dead("tarnor")
  !See("tarnor")
THEN
  RESPONSE #100
    ReallyForceSpell("tarnor",WIZARD_DIMENSION_DOOR)
END

IF
    !Allegiance(Myself,ENEMY)
    OR(12)
        AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
        AttackedBy([PC],DEFAULT)
        AttackedBy([FAMILIAR],DEFAULT)
        AttackedBy([ALLY],DEFAULT)
        AttackedBy([CONTROLLED],DEFAULT)
        AttackedBy([CHARMED],DEFAULT)
        SpellCastOnMe([GOODCUTOFF.0.0.0.0.SUMMONED],0)
        SpellCastOnMe([PC],0)
        SpellCastOnMe([FAMILIAR],0)
        SpellCastOnMe([ALLY],0)
        SpellCastOnMe([CONTROLLED],0)
        SpellCastOnMe([CHARMED],0)
THEN
    RESPONSE #100
        Enemy()
        Continue()
END

IF
    Global("Paranoid","LOCALS",0)
    !Detect(NearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    OR(5)
        HPPercentLT(Myself,100)
        Exists(LastAttackerOf(Myself))
        SpellCast([GOODCUTOFF],0)
        SpellCastPriest([GOODCUTOFF],0)
        SpellCastInnate([GOODCUTOFF],0)
THEN
    RESPONSE #100
        SetGlobal("Paranoid","LOCALS",1)
        DisplayString(Myself,26703) // Damn, where are they?
        Continue()
END

IF
    Global("Paranoid","LOCALS",1)
    !Detect(NearestEnemyOf(Myself))
    !GlobalTimerNotExpired("UndeadHate","LOCALS")
    General(Myself,UNDEAD)
    !AreaCheck("AR1401")
    OR(6)
        InMyArea(Player1)
        InMyArea(Player2)
        InMyArea(Player3)
        InMyArea(Player4)
        InMyArea(Player5)
        InMyArea(Player6)
THEN
    RESPONSE #100
        SetGlobalTimer("UndeadHate","LOCALS",24)
        DisplayString(Myself,62975) // I've heard enough!  Show yourself, whatever you are, so I might destroy you!
        DisplayString(Myself,57171) // I'll kill you for trying to manipulate me!
        ForceSpellRES("wwundead",Myself) // Teleport Field
END

IF
    ActionListEmpty()
    CombatCounter(0)
    !Detect(NearestEnemyOf(Myself))
    !Global("Paranoid","LOCALS",1)
    !Global("Prep","LOCALS",0)
    !GlobalTimerExpired("PrepTimer","LOCALS")
THEN
    RESPONSE #100
        NoAction()
END

IF
    Global("Prep","LOCALS",0)
    CheckStatGT(Myself,17,LEVEL)
    OR(2)
        See(NearestEnemyOf(Myself))
        !CombatCounter(0)
THEN
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_EVIL)
        ReallyForceSpell(Myself,WIZARD_BLUR)
        ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
        ReallyForceSpell(Myself,WIZARD_SHADOW_DOOR)
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        ReallyForceSpell(Myself,WIZARD_SPELL_TRAP)
        Continue()
END

IF
    Global("Prep","LOCALS",0)
    CheckStatGT(Myself,12,LEVEL)
    CheckStatLT(Myself,18,LEVEL)
    OR(2)
        See(NearestEnemyOf(Myself))
        !CombatCounter(0)
THEN
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_EVIL)
        ReallyForceSpell(Myself,WIZARD_BLUR)
        ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        Continue()
END

IF
    CheckStatGT(Myself,12,LEVEL)
    Global("Prep","LOCALS",0)
    Global("Guard","LOCALS",0)
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        CreateCreatureObject("stalke",Myself,0,0,0) // Invisible Stalker
        IncrementGlobal("Guard","LOCALS",1)
        Continue()
    RESPONSE #100
        CreateCreatureObject("elair01",Myself,0,0,0) // Air Elemental
        IncrementGlobal("Guard","LOCALS",1)
        Continue()
    RESPONSE #100
        CreateCreatureObject("elear01",Myself,0,0,0) // Earth Elemental
        IncrementGlobal("Guard","LOCALS",1)
        Continue()
    RESPONSE #100
        CreateCreatureObject("elfir01",Myself,0,0,0) // Fire Elemental
        IncrementGlobal("Guard","LOCALS",1)
        Continue()
    RESPONSE #100
        CreateCreatureObject("skelwa",Myself,0,0,0) // Skeleton Warrior
        IncrementGlobal("Guard","LOCALS",1)
        Continue()
END

IF
    Global("Prep","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobalTimer("PrepTimer","LOCALS",0)
        SetGlobal("Prep","LOCALS",1)
END

IF
    GlobalTimerExpired("PrepTimer","LOCALS")
    !CheckStatGT(Myself,12,LEVEL)
    OR(2)
        See(NearestEnemyOf(Myself))
        !CombatCounter(0)
THEN
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_EVIL)
        ReallyForceSpell(Myself,WIZARD_BLUR)
        ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
        Continue()
END

IF
    GlobalTimerExpired("PrepTimer","LOCALS")
    CheckStatGT(Myself,12,LEVEL)
    OR(2)
        See(NearestEnemyOf(Myself))
        !CombatCounter(0)
THEN
    RESPONSE #100
        DisplayString(Myself,31247) // Tattoo of Power - Spell Immunity
        ApplySpell(Myself,WIZARD_SPELL_IMMUNITY_INVOCATION)
        Continue()
    RESPONSE #100
        DisplayString(Myself,31247) // Tattoo of Power - Spell Immunity
        ApplySpell(Myself,WIZARD_SPELL_IMMUNITY_ENCHANTMENT)
        Continue()
    RESPONSE #500
        DisplayString(Myself,31247) // Tattoo of Power - Spell Immunity
        ApplySpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)
        Continue()
END

IF
    GlobalTimerExpired("PrepTimer","LOCALS")
    Global("Potion","LOCALS",0)
    Allegiance(Myself,ENEMY)
    !HP(Myself,0)
THEN
    RESPONSE #100
        GiveItemCreate("potn42",Myself,1,0,0) // Potion of Regeneration 
        UseItem("potn42",Myself) // Potion of Regeneration 
        SetGlobal("Potion","LOCALS",1)
        Continue()
    RESPONSE #100
        GiveItemCreate("potn11",Myself,1,0,0) // Potion of Invulnerability
        UseItem("potn11",Myself) // Potion of Invulnerability
        SetGlobal("Potion","LOCALS",1)
        Continue()
    RESPONSE #100
        GiveItemCreate("potn34",Myself,1,0,0) // Potion of Magic Protection
        UseItem("potn34",Myself) // Potion of Magic Protection
        SetGlobal("Potion","LOCALS",1)
        Continue()
    RESPONSE #100
        GiveItemCreate("potn35",Myself,1,0,0) // Potion of Magic Shielding
        UseItem("potn35",Myself) // Potion of Magic Shielding
        SetGlobal("Potion","LOCALS",1)
        Continue()
END

IF
    GlobalTimerExpired("PrepTimer","LOCALS")
    !HP(Myself,0)
THEN
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_FIRE)
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_COLD)
        Continue()
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_FIRE)
        Continue()
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_COLD)
        Continue()
    RESPONSE #100
        Continue()
END

IF
    GlobalTimerExpired("PrepTimer","LOCALS")
    !HP(Myself,0)
    CheckStatGT(Myself,12,LEVEL)
THEN
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ACID)
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)
        Continue()
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)
        Continue()
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ACID)
        Continue()
    RESPONSE #100
        Continue()
END

IF
    CheckStatGT(Myself,12,LEVEL)
    GlobalTimerExpired("PrepTimer","LOCALS")
    !HP(Myself,0)
THEN
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_MELF_METEOR)
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
        ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
        ReallyForceSpell(Myself,WIZARD_ARMOR)
        SetGlobalTimer("PrepTimer","LOCALS",4800)
        SetGlobalTimer("Cast","LOCALS",0)
        SetGlobalTimer("TimeStop","LOCALS",0)
        SetGlobalTimer("SpellTrap","LOCALS",0)
        SetGlobalTimer("ProMagic","LOCALS",0)
        SetGlobalTimer("Shadow","LOCALS",0)
        SetGlobalTimer("Fire","LOCALS",0)
        Continue()
END

IF
    !CheckStatGT(Myself,12,LEVEL)
    GlobalTimerExpired("PrepTimer","LOCALS")
    !HP(Myself,0)
THEN
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_MELF_METEOR)
        ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
        ReallyForceSpell(Myself,WIZARD_ARMOR)
        SetGlobalTimer("PrepTimer","LOCALS",4800)
        SetGlobalTimer("Cast","LOCALS",0)
        SetGlobalTimer("TimeStop","LOCALS",0)
        SetGlobalTimer("SpellTrap","LOCALS",0)
        SetGlobalTimer("ProMagic","LOCALS",0)
        SetGlobalTimer("Shadow","LOCALS",0)
        SetGlobalTimer("Fire","LOCALS",0)
        Continue()
END

IF
    CheckStatGT(Myself,17,LEVEL)
    Global("Chain","LOCALS",0)
    OR(8)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
        SpellCastOnMe([GOODCUTOFF],0)
        SpellCastOnMe([PC],0)
        SpellCastOnMe([FAMILIAR],0)
        SpellCastOnMe([ALLY],0)
        SpellCastOnMe([CONTROLLED],0)
        SpellCastOnMe([CHARMED],0)
    !HP(Myself,0)
THEN
    RESPONSE #100
        SetGlobal("Chain","LOCALS",1)
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_FIRE)
        DisplayString(Myself,26328) // Chain Contingency
        ReallyForceSpell(Myself,WIZARD_SPELL_TRAP)
        ReallyForceSpell(Myself,WIZARD_MORDENKAINENS_SWORD)
        ReallyForceSpell(Myself,WIZARD_MISLEAD)
        SetGlobalTimer("SpellTrap","LOCALS",60)
        DisplayString(Myself,40252) // Contingency - Protection from Magical Weapons
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        SetGlobalTimer("ProMagic","LOCALS",24)
    RESPONSE #100
        SetGlobal("Chain","LOCALS",1)
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_FIRE)
        DisplayString(Myself,26328) // Chain Contingency
        ReallyForceSpell(Myself,WIZARD_SPELL_TRAP)
        ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)
        ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)
        SetGlobalTimer("SpellTrap","LOCALS",60)
        DisplayString(Myself,40252) // Contingency - Protection from Magical Weapons
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        SetGlobalTimer("ProMagic","LOCALS",24)
    RESPONSE #100
        SetGlobal("Chain","LOCALS",1)
        DisplayString(Myself,26328) // Chain Contingency
        ReallyForceSpell(Myself,WIZARD_SPELL_TRAP)
        ReallyForceSpell(Myself,WIZARD_ABI_DALZIMS_HORRID_WILTING)
        ReallyForceSpell(Myself,WIZARD_ABI_DALZIMS_HORRID_WILTING)
        SetGlobalTimer("SpellTrap","LOCALS",60)
        DisplayString(Myself,40252) // Contingency - Protection from Magical Weapons
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        SetGlobalTimer("ProMagic","LOCALS",24)
    RESPONSE #100
        SetGlobal("Chain","LOCALS",1)
        DisplayString(Myself,26328) // Chain Contingency
        ReallyForceSpell(Myself,WIZARD_SPELL_TRAP)
        ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)
        ReallyForceSpell(Myself,WIZARD_ABI_DALZIMS_HORRID_WILTING)
        SetGlobalTimer("SpellTrap","LOCALS",60)
        DisplayString(Myself,40252) // Contingency - Protection from Magical Weapons
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        SetGlobalTimer("ProMagic","LOCALS",24)
END

IF
    !CheckStatGT(Myself,17,LEVEL)
    HPPercentLT(Myself,100)
    Global("Contingency","LOCALS",0)
    !HP(Myself,0)
THEN
    RESPONSE #100
        SetGlobal("Contingency","LOCALS",1)
        DisplayString(Myself,29736) // Contingency - Stoneskin
        ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
END

IF
    StateCheck(Myself,STATE_SILENCED)
    HaveSpell(WIZARD_VOCALIZE)
    GlobalTimerExpired("Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(Myself,WIZARD_VOCALIZE)
END

IF
    HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    OR(2)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("ProMagic","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        SetGlobalTimer("ProMagic","LOCALS",24)
END

IF
    HaveSpell(WIZARD_SUMMON_NISHRUU)
    OR(2)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("ProMagic","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        RemoveSpell(WIZARD_SUMMON_NISHRUU)
        SpellNoDec(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        SetGlobalTimer("ProMagic","LOCALS",24)
END

IF
    HaveSpell(WIZARD_TRUE_SIGHT)
    OR(2)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("ProMagic","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        RemoveSpell(WIZARD_TRUE_SIGHT)
        SpellNoDec(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        SetGlobalTimer("ProMagic","LOCALS",24)
END

IF
    HaveSpell(WIZARD_DISINTEGRATE)
    OR(2)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("ProMagic","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        RemoveSpell(WIZARD_DISINTEGRATE)
        SpellNoDec(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        SetGlobalTimer("ProMagic","LOCALS",24)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_STONE_SKIN)
    CheckStatLT(Myself,1,STONESKINS)
    GlobalTimerExpired("Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(Myself,WIZARD_STONE_SKIN)
END

IF
    HaveSpell(WIZARD_TIME_STOP)
    OR(2)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("TimeStop","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("TimeStop","LOCALS",24)
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(Myself,WIZARD_TIME_STOP)
END

IF
    HaveSpell(WIZARD_METEOR_SWARM)
    OR(2)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("TimeStop","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("TimeStop","LOCALS",24)
        SetGlobalTimer("Cast","LOCALS",6)
        RemoveSpell(WIZARD_METEOR_SWARM)
        SpellNoDec(Myself,WIZARD_TIME_STOP)
END

IF
    HaveSpell(WIZARD_GATE)
    OR(2)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("TimeStop","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("TimeStop","LOCALS",24)
        SetGlobalTimer("Cast","LOCALS",6)
        RemoveSpell(WIZARD_GATE)
        SpellNoDec(Myself,WIZARD_TIME_STOP)
END

IF
    HaveSpell(WIZARD_SPELL_TRAP)
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("SpellTrap","LOCALS")
    OR(2)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("SpellTrap","LOCALS",60)
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(Myself,WIZARD_SPELL_TRAP)
END

IF
    HaveSpell(WIZARD_SPELL_TURNING)
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("SpellTrap","LOCALS")
    OR(2)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("SpellTrap","LOCALS",60)
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(Myself,WIZARD_SPELL_TURNING)
END

IF
    HaveSpell(WIZARD_SPELL_DEFLECTION)
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("SpellTrap","LOCALS")
    OR(2)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("SpellTrap","LOCALS",60)
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(Myself,WIZARD_SPELL_DEFLECTION)
END

IF
    HaveSpell(WIZARD_MINOR_SPELL_TURNING)
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("SpellTrap","LOCALS")
    OR(2)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("SpellTrap","LOCALS",60)
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(Myself,WIZARD_MINOR_SPELL_TURNING)
END

IF
    Allegiance(Myself,ENEMY)
    OR(2)
        Detect([PC])
        Detect(NearestEnemyOf(Myself))
    !See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_TRUE_SIGHT)
    GlobalTimerExpired("Cast","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(Myself,WIZARD_TRUE_SIGHT)
END

IF
    CheckStatGT(Myself,13,LEVEL)
    GlobalTimerExpired("Cast","LOCALS")
    Global("Sequencer","LOCALS",0)
    OR(2)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        SetGlobal("Sequencer","LOCALS",1)
        DisplayString(Myself,25951) // Spell Sequencer
        ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)
        ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)
        ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)
END

IF
    !CheckStat(SixthNearestEnemyOf(Myself),0,STONESKINS)
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
    See(SixthNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    !CheckStat(FifthNearestEnemyOf(Myself),0,STONESKINS)
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
    See(FifthNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    !CheckStat(FourthNearestEnemyOf(Myself),0,STONESKINS)
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
    See(FourthNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    !CheckStat(ThirdNearestEnemyOf(Myself),0,STONESKINS)
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
    See(ThirdNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    !CheckStat(SecondNearestEnemyOf(Myself),0,STONESKINS)
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
    See(SecondNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    !CheckStat(NearestEnemyOf(Myself),0,STONESKINS)
    !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
    See(NearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    !CheckStat(NearestEnemyOfType([GOODCUTOFF.0.0.BARD]),0,STONESKINS)
    !StateCheck(NearestEnemyOfType([GOODCUTOFF.0.0.BARD]),STATE_IMPROVEDINVISIBILITY)
    CheckStat(NearestEnemyOfType([GOODCUTOFF.0.0.BARD]),0,SANCTUARY)
    See(NearestEnemyOfType([GOODCUTOFF.0.0.BARD]))
    False()
THEN
    RESPONSE #100
END

IF
    !CheckStat(NearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]),0,STONESKINS)
    !StateCheck(NearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]),STATE_IMPROVEDINVISIBILITY)
    CheckStat(NearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]),0,SANCTUARY)
    See(NearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]))
    False()
THEN
    RESPONSE #100
END

IF
    !CheckStat(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]),0,STONESKINS)
    !StateCheck(SecondNearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]),STATE_IMPROVEDINVISIBILITY)
    CheckStat(SecondNearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]),0,SANCTUARY)
    See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
    False()
THEN
    RESPONSE #100
END

IF
    !CheckStat(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]),0,STONESKINS)
    !StateCheck(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]),STATE_IMPROVEDINVISIBILITY)
    CheckStat(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]),0,SANCTUARY)
    See(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
    False()
THEN
    RESPONSE #100
END

IF
    !CheckStat(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]),0,STONESKINS)
    !StateCheck(SecondNearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]),STATE_IMPROVEDINVISIBILITY)
    CheckStat(SecondNearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]),0,SANCTUARY)
    See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
    False()
THEN
    RESPONSE #100
END

IF
    !CheckStat(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]),0,STONESKINS)
    !StateCheck(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]),STATE_IMPROVEDINVISIBILITY)
    CheckStat(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]),0,SANCTUARY)
    See(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
    False()
THEN
    RESPONSE #100
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_SPELL_STRIKE)
    Allegiance(Myself,ENEMY)
    !Allegiance(LastSeenBy(Myself),ENEMY)
    OR(2)
        HasBounceEffects(LastSeenBy(Myself))
        HasImmunityEffects(LastSeenBy(Myself))
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_PIERCE_SHIELD)
    Allegiance(Myself,ENEMY)
    !Allegiance(LastSeenBy(Myself),ENEMY)
    OR(2)
        HasBounceEffects(LastSeenBy(Myself))
        HasImmunityEffects(LastSeenBy(Myself))
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_WARDING_WHIP)
    Allegiance(Myself,ENEMY)
    !Allegiance(LastSeenBy(Myself),ENEMY)
    OR(2)
        HasBounceEffects(LastSeenBy(Myself))
        HasImmunityEffects(LastSeenBy(Myself))
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)
    Allegiance(Myself,ENEMY)
    !Allegiance(LastSeenBy(Myself),ENEMY)
    OR(2)
        HasBounceEffects(LastSeenBy(Myself))
        HasImmunityEffects(LastSeenBy(Myself))
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_SECRET_WORD)
    Allegiance(Myself,ENEMY)
    !Allegiance(LastSeenBy(Myself),ENEMY)
    OR(2)
        HasBounceEffects(LastSeenBy(Myself))
        HasImmunityEffects(LastSeenBy(Myself))
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_SPELL_THRUST)
    Allegiance(Myself,ENEMY)
    !Allegiance(LastSeenBy(Myself),ENEMY)
    OR(2)
        HasBounceEffects(LastSeenBy(Myself))
        HasImmunityEffects(LastSeenBy(Myself))
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_BREACH)
    Allegiance(Myself,ENEMY)
    !Allegiance(LastSeenBy(Myself),ENEMY)
    OR(3)
        HasBounceEffects(LastSeenBy(Myself))
        HasImmunityEffects(LastSeenBy(Myself))
        !CheckStat(LastSeenBy(Myself),0,STONESKINS)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_BREACH)
END

IF
    !Global("Paranoid","LOCALS",0)
    !See(NearestEnemyOf(Myself))
    See(Myself)
    False()
THEN
    RESPONSE #100
END

IF
    OR(8)
        !StateCheck(SixthNearestEnemyOf(Myself),STATE_BLESS)
        !StateCheck(SixthNearestEnemyOf(Myself),STATE_CHANT)
        !StateCheck(SixthNearestEnemyOf(Myself),STATE_DRAWUPONHOLYMIGHT)
        !StateCheck(SixthNearestEnemyOf(Myself),STATE_BLUR)
        !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
        !CheckStat(SixthNearestEnemyOf(Myself),0,STONESKINS)
        HasBounceEffects(SixthNearestEnemyOf(Myself))
        HasImmunityEffects(SixthNearestEnemyOf(Myself))
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
    See(SixthNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    OR(8)
        !StateCheck(FifthNearestEnemyOf(Myself),STATE_BLESS)
        !StateCheck(FifthNearestEnemyOf(Myself),STATE_CHANT)
        !StateCheck(FifthNearestEnemyOf(Myself),STATE_DRAWUPONHOLYMIGHT)
        !StateCheck(FifthNearestEnemyOf(Myself),STATE_BLUR)
        !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
        !CheckStat(FifthNearestEnemyOf(Myself),0,STONESKINS)
        HasBounceEffects(FifthNearestEnemyOf(Myself))
        HasImmunityEffects(FifthNearestEnemyOf(Myself))
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
    See(FifthNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    OR(8)
        !StateCheck(FourthNearestEnemyOf(Myself),STATE_BLESS)
        !StateCheck(FourthNearestEnemyOf(Myself),STATE_CHANT)
        !StateCheck(FourthNearestEnemyOf(Myself),STATE_DRAWUPONHOLYMIGHT)
        !StateCheck(FourthNearestEnemyOf(Myself),STATE_BLUR)
        !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
        !CheckStat(FourthNearestEnemyOf(Myself),0,STONESKINS)
        HasBounceEffects(FourthNearestEnemyOf(Myself))
        HasImmunityEffects(FourthNearestEnemyOf(Myself))
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
    See(FourthNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    OR(8)
        !StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLESS)
        !StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHANT)
        !StateCheck(ThirdNearestEnemyOf(Myself),STATE_DRAWUPONHOLYMIGHT)
        !StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLUR)
        !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
        !CheckStat(ThirdNearestEnemyOf(Myself),0,STONESKINS)
        HasBounceEffects(ThirdNearestEnemyOf(Myself))
        HasImmunityEffects(ThirdNearestEnemyOf(Myself))
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
    See(ThirdNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    OR(8)
        !StateCheck(SecondNearestEnemyOf(Myself),STATE_BLESS)
        !StateCheck(SecondNearestEnemyOf(Myself),STATE_CHANT)
        !StateCheck(SecondNearestEnemyOf(Myself),STATE_DRAWUPONHOLYMIGHT)
        !StateCheck(SecondNearestEnemyOf(Myself),STATE_BLUR)
        !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
        !CheckStat(SecondNearestEnemyOf(Myself),0,STONESKINS)
        HasBounceEffects(SecondNearestEnemyOf(Myself))
        HasImmunityEffects(SecondNearestEnemyOf(Myself))
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
    See(SecondNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    OR(8)
        !StateCheck(NearestEnemyOf(Myself),STATE_BLESS)
        !StateCheck(NearestEnemyOf(Myself),STATE_CHANT)
        !StateCheck(NearestEnemyOf(Myself),STATE_DRAWUPONHOLYMIGHT)
        !StateCheck(NearestEnemyOf(Myself),STATE_BLUR)
        !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
        !CheckStat(NearestEnemyOf(Myself),0,STONESKINS)
        HasBounceEffects(NearestEnemyOf(Myself))
        HasImmunityEffects(NearestEnemyOf(Myself))
    !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
    See(NearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    Allegiance(Myself,ENEMY)
    OR(2)
        !Global("Paranoid","LOCALS",0)
        !Allegiance(LastSeenBy(Myself),ENEMY)
    HaveSpell(WIZARD_DISPEL_MAGIC)
    OR(8)
        !StateCheck(LastSeenBy(Myself),STATE_BLESS)
        !StateCheck(LastSeenBy(Myself),STATE_CHANT)
        !StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
        !StateCheck(LastSeenBy(Myself),STATE_BLUR)
        !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
        !CheckStat(LastSeenBy(Myself),0,STONESKINS)
        HasBounceEffects(LastSeenBy(Myself))
        HasImmunityEffects(LastSeenBy(Myself))
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    Allegiance(Myself,ENEMY)
    OR(2)
        !Allegiance(LastSeenBy(Myself),ENEMY)
        !Global("Paranoid","LOCALS",0)
    HaveSpell(WIZARD_FIREBALL)
    OR(8)
        !StateCheck(LastSeenBy(Myself),STATE_BLESS)
        !StateCheck(LastSeenBy(Myself),STATE_CHANT)
        !StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
        !StateCheck(LastSeenBy(Myself),STATE_BLUR)
        !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
        !CheckStat(LastSeenBy(Myself),0,STONESKINS)
        HasBounceEffects(LastSeenBy(Myself))
        HasImmunityEffects(LastSeenBy(Myself))
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        SetGlobalTimer("Remove","LOCALS",24)
        RemoveSpell(WIZARD_FIREBALL)
        SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    Allegiance(Myself,ENEMY)
    OR(2)
        !Global("Paranoid","LOCALS",0)
        !Allegiance(LastSeenBy(Myself),ENEMY)
    HaveSpell(WIZARD_HASTE)
    OR(8)
        !StateCheck(LastSeenBy(Myself),STATE_BLESS)
        !StateCheck(LastSeenBy(Myself),STATE_CHANT)
        !StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
        !StateCheck(LastSeenBy(Myself),STATE_BLUR)
        !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
        !CheckStat(LastSeenBy(Myself),0,STONESKINS)
        HasBounceEffects(LastSeenBy(Myself))
        HasImmunityEffects(LastSeenBy(Myself))
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        SetGlobalTimer("Remove","LOCALS",24)
        RemoveSpell(WIZARD_HASTE)
        SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_DEATH_SPELL)
    See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
END

IF
    OR(2)
        !Detect(NearestEnemyOf(Myself))
        !Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        NoAction()
END

IF
    !HasBounceEffects(SixthNearestEnemyOf(Myself))
    !HasImmunityEffects(SixthNearestEnemyOf(Myself))
    CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
    See(SixthNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    !HasBounceEffects(FifthNearestEnemyOf(Myself))
    !HasImmunityEffects(FifthNearestEnemyOf(Myself))
    CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
    See(FifthNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    !HasBounceEffects(FourthNearestEnemyOf(Myself))
    !HasImmunityEffects(FourthNearestEnemyOf(Myself))
    CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
    See(FourthNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    !HasBounceEffects(ThirdNearestEnemyOf(Myself))
    !HasImmunityEffects(ThirdNearestEnemyOf(Myself))
    CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
    See(ThirdNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    !HasBounceEffects(SecondNearestEnemyOf(Myself))
    !HasImmunityEffects(SecondNearestEnemyOf(Myself))
    CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
    See(SecondNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    !HasBounceEffects(NearestEnemyOf(Myself))
    !HasImmunityEffects(NearestEnemyOf(Myself))
    CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
    !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
    CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
    See(NearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
END

IF
    !HasBounceEffects(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
    !HasImmunityEffects(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
    CheckStatLT(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]),50,RESISTMAGIC)
    !StateCheck(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]),STATE_IMPROVEDINVISIBILITY)
    CheckStat(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]),0,SANCTUARY)
    See(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
    False()
THEN
    RESPONSE #100
END

IF
    !HasBounceEffects(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
    !HasImmunityEffects(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
    !StateCheck(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]),STATE_IMPROVEDINVISIBILITY)
    CheckStat(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]),0,SANCTUARY)
    See(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
    False()
THEN
    RESPONSE #100
END

IF
    !Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        NoAction()
END

IF
    Allegiance(LastSeenBy(Myself),ENEMY)
THEN
    RESPONSE #100
        NoAction()
END

IF
    CheckStatGT(Myself,15,LEVEL)
    GlobalTimerExpired("Cast","LOCALS")
    Global("Trigger","LOCALS",0)
    CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobal("Trigger","LOCALS",1)
        DisplayString(Myself,26243) // Spell Trigger
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAOS)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_IMPRISONMENT)
    Range(LastSeenBy(Myself),2)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_IMPRISONMENT)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_GREATER_MALISON)
    CheckStatLT(LastSeenBy(Myself),5,SAVEVSSPELL)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)
    CheckStatLT(LastSeenBy(Myself),50,MAGICDAMAGERESISTANCE)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_SIMULACRUM)
    CheckStatLT(LastSeenBy(Myself),50,MAGICDAMAGERESISTANCE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        RemoveSpell(WIZARD_SIMULACRUM)
        SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_SUMMON_FIEND)
    CheckStatLT(LastSeenBy(Myself),50,MAGICDAMAGERESISTANCE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        RemoveSpell(WIZARD_SUMMON_FIEND)
        SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_MAZE)
    CheckStatLT(LastSeenBy(Myself),50,MAGICDAMAGERESISTANCE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        RemoveSpell(WIZARD_MAZE)
        SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_WAIL_OF_THE_BANSHEE)
    Range(LastSeenBy(Myself),30)
    CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(Myself,WIZARD_WAIL_OF_THE_BANSHEE)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    OR(2)
        HaveSpell(WIZARD_SYMBOL_STUN)
        HaveSpell(WIZARD_NPC_SYMBOL_STUN)
    CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)
        Spell(LastSeenBy(Myself),WIZARD_NPC_SYMBOL_STUN)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)
    CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    OR(2)
        HaveSpell(WIZARD_SYMBOL_DEATH)
        HaveSpell(WIZARD_NPC_SYMBOL_DEATH)
    CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
    CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)
        Spell(LastSeenBy(Myself),WIZARD_NPC_SYMBOL_DEATH)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_KILL)
    CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    OR(2)
        HaveSpell(WIZARD_SYMBOL_FEAR)
        HaveSpell(WIZARD_NPC_SYMBOL_FEAR)
    CheckStatGT(LastSeenBy(Myself),4,SAVEVSSPELL)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy,WIZARD_SYMBOL_FEAR)
        Spell(LastSeenBy,WIZARD_NPC_SYMBOL_FEAR)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_MORDENKAINENS_SWORD)
    CheckStatGT(LastSeenBy(Myself),-15,ARMORCLASS)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(Myself,WIZARD_MORDENKAINENS_SWORD)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_SPHERE_OF_CHAOS)
    CheckStatGT(LastSeenBy(Myself),-15,ARMORCLASS)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        RemoveSpell(WIZARD_SPHERE_OF_CHAOS)
        SpellNoDec(Myself,WIZARD_MORDENKAINENS_SWORD)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_SUMMON_EFREET)
    CheckStatGT(LastSeenBy(Myself),-15,ARMORCLASS)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        RemoveSpell(WIZARD_SUMMON_EFREET)
        SpellNoDec(Myself,WIZARD_MORDENKAINENS_SWORD)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_PRISMATIC_SPRAY)
    CheckStatGT(LastSeenBy(Myself),-15,ARMORCLASS)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        RemoveSpell(WIZARD_PRISMATIC_SPRAY)
        SpellNoDec(Myself,WIZARD_MORDENKAINENS_SWORD)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_CHAOS)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    !StateCheck(LastSeenBy(Myself),STATE_BERSERK)
    CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
    !HasItemEquiped("AMUL17",LastSeenBy(Myself)) // Greenstone Amulet
    !HasItemEquiped("LEAT20",LastSeenBy(Myself)) // Aeger's Hide +3
    !HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
    !HasItemEquipedReal("SW1H54",LastSeenBy(Myself)) // The Equalizer
    !HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
    !HasItemEquipedReal("SW2H21",LastSeenBy(Myself)) // Psion's Blade +5
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_CHAOS)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_FINGER_OF_DEATH)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_DOMINATION)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    !StateCheck(LastSeenBy(Myself),STATE_BERSERK)
    CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
    !Class(LastSeenBy(Myself),MONK)
    !Kit(LastSeenBy(Myself),INQUISITOR)
    !HasItemEquiped("HELM06",LastSeenBy(Myself)) // Helm of Charm Protection
    !HasItemEquiped("MISCBC",LastSeenBy(Myself)) // Blackrazor
    !HasItemEquiped("NPCHAN",LastSeenBy(Myself)) // Corthala Family Armor
    !HasItemEquiped("REAVER",LastSeenBy(Myself)) // Unholy Reaver
    !HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
    !HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
    !HasItemEquipedReal("SW1H35",LastSeenBy(Myself)) // Adjatha The Drinker +2
    !HasItemEquipedReal("SW1H54",LastSeenBy(Myself)) // The Equalizer
    !HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_DOMINATION)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_POLYMORPH_OTHER)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSPOLY)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_POLYMORPH_OTHER)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_CONFUSION)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    !StateCheck(LastSeenBy(Myself),STATE_BERSERK)
    CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
    !HasItemEquiped("AMUL17",LastSeenBy(Myself)) // Greenstone Amulet
    !HasItemEquiped("LEAT20",LastSeenBy(Myself)) // Aeger's Hide +3
    !HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
    !HasItemEquipedReal("SW1H54",LastSeenBy(Myself)) // The Equalizer
    !HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
    !HasItemEquipedReal("SW2H21",LastSeenBy(Myself)) // Psion's Blade +5
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_FLESH_TO_STONE)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSPOLY)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_FLESH_TO_STONE)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_DISINTEGRATE)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_DISINTEGRATE)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_CHAIN_LIGHTNING)
    CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
    !HasItemEquiped("CLCK24",LastSeenBy(Myself)) // Cloak of Reflection
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_CONE_OF_COLD)
    CheckStatLT(LastSeenBy(Myself),50,RESISTCOLD)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_HOLD_PERSON)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    !Kit(LastSeenBy(Myself),INQUISITOR)
    !HasItemEquiped("FREERING",LastSeenBy(Myself)) // Ring of Free Action
    !HasItemEquiped("ROSSRING",LastSeenBy(Myself)) // Ring of Free Action
    !HasItemEquiped("RING09",LastSeenBy(Myself)) // Ring of Free Action
    !HasItemEquiped("NPSW01",LastSeenBy(Myself)) // Sword of Arvoreen
    OR(6)
        Class(LastSeenBy(Myself),RANGER_ALL)
        Class(LastSeenBy(Myself),FIGHTER_ALL)
        Class(LastSeenBy(Myself),PALADIN)
        Class(LastSeenBy(Myself),THIEF)
        Kit(LastSeenBy(Myself),BARBARIAN)
        Gender(LastSeenBy(Myself),SUMMONED)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_HOLD_PERSON)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_FLAME_ARROW)
    CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_SKULL_TRAP)
    CheckStatLT(LastSeenBy(Myself),50,MAGICDAMAGERESISTANCE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_SKULL_TRAP)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_SUN_FIRE)
    Range(LastSeenBy(Myself),30)
    CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(Myself,WIZARD_SUN_FIRE)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_LIGHTNING_BOLT)
    CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
    !HasItemEquiped("CLCK24",LastSeenBy(Myself)) // Cloak of Reflection
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("Shadow","LOCALS")
    HaveSpell(WIZARD_MISLEAD)
    See(Myself)
    OR(3)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
        Global("Paranoid","LOCALS",1)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        SetGlobalTimer("Shadow","LOCALS",32)
        Spell(Myself,WIZARD_MISLEAD)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("Shadow","LOCALS")
    HaveSpell(WIZARD_SHADOW_DOOR)
    See(Myself)
    OR(3)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
        Global("Paranoid","LOCALS",1)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        SetGlobalTimer("Shadow","LOCALS",32)
        Spell(Myself,WIZARD_SHADOW_DOOR)
END

IF
    !Detect(NearestEnemyOf(Myself))
    HPPercentLT(Myself,100)
    GlobalTimerExpired("Cast","LOCALS")
THEN
    RESPONSE #100
        GiveItemCreate("potn52",Myself,1,0,0) // Potion of Extra Healing
        UseItem("potn52",Myself) // Potion of Extra Healing
        SetGlobalTimer("Cast","LOCALS",6)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_ANIMATE_DEAD)
    CheckStatGT(LastSeenBy(Myself),-10,ARMORCLASS)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_ANIMATE_DEAD)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_INVISIBLE_STALKER)
    CheckStatGT(LastSeenBy(Myself),-10,ARMORCLASS)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_INVISIBLE_STALKER)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_WYVERN_CALL)
    CheckStatGT(LastSeenBy(Myself),-10,ARMORCLASS)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_WYVERN_CALL)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_SPIDER_SPAWN)
    CheckStatGT(LastSeenBy(Myself),-10,ARMORCLASS)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_SPIDER_SPAWN)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_MONSTER_SUMMONING_3)
    CheckStatGT(LastSeenBy(Myself),-10,ARMORCLASS)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_MONSTER_SUMMONING_3)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    GlobalTimerExpired("Fire","LOCALS")
    HaveSpell(WIZARD_FIRE_SHIELD_RED)
    See(Myself)
    OR(3)
        See(NearestEnemyOf(Myself))
        HPPercentLT(Myself,100)
        Global("Paranoid","LOCALS",1)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        SetGlobalTimer("Fire","LOCALS",32)
        Spell(Myself,WIZARD_FIRE_SHIELD_RED)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_SLOW)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    !Class(LastSeenBy(Myself),MONK)
    !HasItemEquiped("FREERING",LastSeenBy(Myself)) // Ring of Free Action
    !HasItemEquiped("ROSSRING",LastSeenBy(Myself)) // Ring of Free Action
    !HasItemEquiped("RING09",LastSeenBy(Myself)) // Ring of Free Action
    !HasItemEquiped("NPSW01",LastSeenBy(Myself)) // Sword of Arvoreen
    OR(6)
        Class(LastSeenBy(Myself),RANGER_ALL)
        Class(LastSeenBy(Myself),FIGHTER_ALL)
        Class(LastSeenBy(Myself),PALADIN)
        Class(LastSeenBy(Myself),THIEF)
        Kit(LastSeenBy(Myself),BARBARIAN)
        Gender(LastSeenBy(Myself),SUMMONED)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_WEB)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    !Kit(LastSeenBy(Myself),INQUISITOR)
    !HasItemEquiped("ANTIWEB",LastSeenBy(Myself)) // No such index
    !HasItemEquiped("FREERING",LastSeenBy(Myself)) // Ring of Free Action
    !HasItemEquiped("ROSSRING",LastSeenBy(Myself)) // Ring of Free Action
    !HasItemEquiped("RING09",LastSeenBy(Myself)) // Ring of Free Action
    !HasItemEquiped("NPSW01",LastSeenBy(Myself)) // Sword of Arvoreen
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_WEB)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_STINKING_CLOUD)
    CheckStatGT(LastSeenBy(Myself),1,SAVEVSSPELL)
    !Kit(LastSeenBy(Myself),INQUISITOR)
    !HasItemEquiped("ANTIWEB",LastSeenBy(Myself)) // No such index
    !HasItemEquiped("FREERING",LastSeenBy(Myself)) // Ring of Free Action
    !HasItemEquiped("ROSSRING",LastSeenBy(Myself)) // Ring of Free Action
    !HasItemEquiped("RING09",LastSeenBy(Myself)) // Ring of Free Action
    !HasItemEquiped("NPSW01",LastSeenBy(Myself)) // Sword of Arvoreen
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_CLOUDKILL)
    HasItem("LICH",Myself) // No such index
    CheckStatLT(LastSeenBy(Myself),50,MAGICDAMAGERESISTANCE)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_MELF_ACID_ARROW)
    CheckStatLT(LastSeenBy(Myself),50,RESISTACID)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
    CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_CHROMATIC_ORB)
    CheckStatGT(LastSeenBy(Myself),6,SAVEVSSPELL)
    CheckStatLT(LastSeenBy(Myself),50,RESISTACID)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_MONSTER_SUMMONING_2)
    CheckStatGT(LastSeenBy(Myself),-5,ARMORCLASS)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_MONSTER_SUMMONING_2)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_MONSTER_SUMMONING_1)
    CheckStatGT(LastSeenBy(Myself),-5,ARMORCLASS)
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_MONSTER_SUMMONING_1)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_MAGIC_MISSILE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
    GlobalTimerExpired("Cast","LOCALS")
    HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
    !RandomNum(20,0)
THEN
    RESPONSE #100
        SetGlobalTimer("Cast","LOCALS",6)
        Spell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
END

IF
    HasItem("melfmet",Myself) // Melf's Minute Meteor
    !HasBounceEffects(LastSeenBy(Myself))
    !GlobalTimerExpired("Cast","LOCALS")
    ActionListEmpty()
    !StateCheck(Myself,STATE_INVISIBLE)
THEN
    RESPONSE #100
        EquipRanged()
        Attack(LastSeenBy(Myself))
END

IF
    ActionListEmpty()
THEN
    RESPONSE #100
        RandomWalk()
END

