IF
	Global("KeepPlot","GLOBAL",11)
	Global("RoenallSpawn","AR1304",0)
THEN
	RESPONSE #100
		ActionOverride("kpcapt02",JumpToPoint([1916.1865]))
		SetGlobal("RoenallSpawn","AR1304",1)
		OpenDoor("Bridge01")
		CreateCreature("KPSOLD03",[3716.2770],14) // de'Arnise Guard
		CreateCreature("KPSOLD03",[3648.2856],14) // de'Arnise Guard
		CreateCreature("KPSOLD04",[3675.2781],14) // de'Arnise Guard
		CreateCreature("KPSOLD04",[3630.2702],14) // de'Arnise Guard
		CreateCreature("KPSOLD04",[3636.2900],14) // de'Arnise Guard
		CreateCreature("KPROEN01",[3862.2948],6) // Lord Roenall
		CreateCreature("b#roen02",[3905.3072],6)
		CreateCreature("b#roen03",[3992.2983],6)
		CreateCreature("b#roen04",[3894.2960],6)
		CreateCreature("b#roen05",[3981.2883],6)
		CreateCreature("b#roen06",[3845.3035],6)
		CreateCreature("b#roen07",[3815.3035],6)
END


