IF
	Global("KeepPlot","GLOBAL",11)
	Global("RoenallSpawn","AR1304",0)
THEN
	RESPONSE #100
		ActionOverride("kpcapt02",JumpToPoint([1916.1865]))
		SetGlobal("RoenallSpawn","AR1304",1)
		OpenDoor("Bridge01")
		CreateCreature("KPSOLD03",[3716.2770],14) // de'Arnise Guard
		CreateCreature("KPSOLD03",[3648.2856],14) // de'Arnise Guard
		CreateCreature("KPSOLD04",[3675.2781],14) // de'Arnise Guard
		CreateCreature("KPSOLD04",[3630.2702],14) // de'Arnise Guard
		CreateCreature("KPSOLD04",[3636.2900],14) // de'Arnise Guard
		CreateCreature("KPROEN01",[3862.2948],6) // Lord Roenall
		CreateCreature("KPROEN02",[3815.3035],6) // Roenall Guard
		CreateCreature("KPROEN02",[3845.3035],6) // Roenall Guard
		CreateCreature("KPROEN03",[3894.2960],6) // Roenall Guard
		CreateCreature("KPROEN04",[3981.2883],6) // Roenall Soldier
		CreateCreature("KPROEN05",[3992.2983],6) // Roenall Soldier
		CreateCreature("KPROEN05",[3905.3072],6) // Roenall Soldier
END


