////////////////////////////////////////
// Buff
////////////////////////////////////////

IF
  CheckStatLT(Myself,1,STONESKINS)
  Global("RiatavinFight","GLOBAL",1)
  !GlobalTimerNotExpired("Prep","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Prep","LOCALS",6)
    ForceSpell(Myself,WIZARD_STONE_SKIN)
    ForceSpell(Myself,WIZARD_SHIELD)
    ForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)
    ForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)
END

////////////////////////////////////////
// Enemy Global
////////////////////////////////////////

IF
  Global("RiatavinFight","GLOBAL",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

////////////////////////////////////////
// Teleport Next To Player1
////////////////////////////////////////

IF
  !Detect([GOODCUTOFF])
  !See([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    ReallyForceSpell(Player1,WIZARD_DIMENSION_DOOR)
END

////////////////////////////////////////
// Spell Enemy
////////////////////////////////////////

IF
  See([PC])
  Allegiance(Myself,ENEMY)
  Allegiance(LastSeenBy(Myself),PC)
  !CheckStatLT(LastSeenBy(Myself),34,RESISTMAGIC)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    ForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
END

IF
  See([PC])
  Allegiance(Myself,ENEMY)
  Allegiance(LastSeenBy(Myself),PC)
  CheckStatLT(LastSeenBy(Myself),34,RESISTMAGIC)
  !HasItemEquiped("CLCK26",LastSeenBy(Myself))
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #34
    SetGlobalTimer("Cast","LOCALS",6)
    ForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
  RESPONSE #33
    SetGlobalTimer("Cast","LOCALS",6)
    ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
  RESPONSE #33
    SetGlobalTimer("Cast","LOCALS",6)
    ForceSpell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END