////////////////////////////////////////
// Kiser Jhaeri (Top Floor)
////////////////////////////////////////

////////////////////////////////////////
// Detect Enemy
////////////////////////////////////////

IF
  Heard([ANYONE],111)
THEN
  RESPONSE #100
    MoveToObject(NearestEnemyOf(Myself))
END

IF
  Detect([PC])
  Allegiance(Myself,ENEMY)
  Allegiance(LastSeenBy(Myself),PC)
  OR(6)
    !See(LastSeenBy(Myself))
    StateCheck([PC],STATE_INVISIBLE)
    StateCheck([PC],STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,26703)
    MoveToObject(LastSeenBy(Myself))
END

////////////////////////////////////////
// Use Items
////////////////////////////////////////

IF
  HPPercentLT(Myself,76)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    GiveItemCreate("potn55",Myself,1,0,0)
    DisplayStringHead(Myself,46150)
    UseItem("potn55",Myself)
END

////////////////////////////////////////
// Hide/Invisible
////////////////////////////////////////

IF
  See(NearestEnemyOf(Myself))
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    GiveItemCreate("potn10",Myself,1,0,0)
    DisplayStringHead(Myself,46150)
    UseItem("potn10",Myself)
END

IF
  See([PC])
  Allegiance(Myself,ENEMY)
  !Range(LastSeenBy(Myself),1)
  OR(2)
    StateCheck(Myself,STATE_INVISIBLE)
    StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    MoveToObject(LastSeenBy(Myself))
END

////////////////////////////////////////
// Use Specials
////////////////////////////////////////

IF
  Range(NearestEnemyOf(Myself),1)
  Allegiance(Myself,ENEMY)
  HaveSpell(ASSASSIN_POISON)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    Spell(Myself,ASSASSIN_POISON)
END

////////////////////////////////////////
// Attack Enemy/Backstab
////////////////////////////////////////

IF
  See([PC])
  Allegiance(Myself,ENEMY)
  Allegiance(LastSeenBy(Myself),PC)
THEN
  RESPONSE #100
    Attack(LastSeenBy(Myself))
END
