////////////////////////////////////////
// Original Script
////////////////////////////////////////

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Heard([ANYONE],81)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  Heard([ANYONE],89)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

////////////////////////////////////////
// Mage targeting
////////////////////////////////////////

IF
  OR(9)
    See(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(ThirdNearestEnemyOfType([0.0.0.SORCERER]))
    See(SecondNearestEnemyOfType([0.0.0.SORCERER]))
    See(NearestEnemyOfType([0.0.0.SORCERER]))
    See(ThirdNearestEnemyOfType([0.0.0.BARD_ALL]))
    See(SecondNearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
  !Range(LastSeenBy(Myself),7)
THEN
  RESPONSE #100
    EquipRanged()
    AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
  OR(9)
    See(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(ThirdNearestEnemyOfType([0.0.0.SORCERER]))
    See(SecondNearestEnemyOfType([0.0.0.SORCERER]))
    See(NearestEnemyOfType([0.0.0.SORCERER]))
    See(ThirdNearestEnemyOfType([0.0.0.BARD_ALL]))
    See(SecondNearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
  Range(LastSeenBy(Myself),7)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

////////////////////////////////////////
// Use Potion
////////////////////////////////////////

IF
  HPPercentLT(Myself,50)
  HasItem("potn52",Myself)
  !GlobalTimerNotExpired("Cast","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Cast","LOCALS",6)
    DisplayStringHead(Myself,46150)
    UseItem("potn52",Myself)
END