////////////////////////////////////////
// Becoming Fallen
////////////////////////////////////////

// Paladin
// FIXME: l'indentation de Global("b#SamilMove","GLOBAL",2) laisse penser qu'il fait parti du OR(2) mais en étant sur la troisième ligne
// Il faudrait investiguer pour connaître l'intention de l'auteur
// est-ce une condition nécessaire et dans ce cas il faut réduire l'indentation
// ou le OR(2) devrait être un OR(3) ? dans ce cas, c'est impactant

IF
  Class(Player1,PALADIN_ALL)
  !FallenPaladin(Player1)
  OR(2)
    Global("b#SamilWarned","GLOBAL",2)
    Global("b#SamilChellenged","GLOBAL",2)
    Global("b#SamilMove","GLOBAL",2)
  Global("b#LostHood","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("b#LostHood","GLOBAL",0)
    RemovePaladinHood()
END

// Ranger

IF
  Class(Player1,RANGER_ALL)
  !FallenPaladin(Player1)
  OR(2)
    Global("b#SamilWarned","GLOBAL",2)
    Global("b#SamilChellenged","GLOBAL",2)
    Global("b#SamilMove","GLOBAL",2)
  Global("b#LostHood","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("b#LostHood","GLOBAL",0)
    RemoveRangerHood()
END